version: 2.1
jobs:
  build-linux:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - haskell-v1-linux-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - haskell-v1-linux-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Build
          command: stack --no-terminal build
      - save_cache:
          name: Cache Dependencies
          key: haskell-v1-linux-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"

  build-osx:
    macos:
      xcode: "11.2.1"
    steps:
      - checkout
      - run:
          name: Install deps
          command: brew install haskell-stack pcre pkg-config
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - haskell-v1-osx-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - haskell-v1-osx-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Build
          command: stack --no-terminal build
      - save_cache:
          name: Cache Dependencies
          key: haskell-v1-osx-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"

workflows:
  version: 2
  build_all:
    jobs:
      - build-linux
      - build-osx

  test-daily:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: master
    jobs:
      - build-linux
      - build-osx
