name: Build and run
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed if using OIDC to get release secrets.

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        with:
          ghc-version: 8.10.7
          enable-stack: true

      - uses: launchdarkly/gh-actions/actions/verify-hello-app@verify-hello-app-v1.0.0
        with:
          use_server_key: true
          role_arn: ${{ vars.AWS_ROLE_ARN }}
          command: stack --no-terminal run
